language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
      
os:
  - linux
  - osx
    
cache: cargo

addons:
  apt:
    packages:
      - libsdl2-dev
      - libsdl2-image-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install sdl2 sdl2_image; fi
