language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
script:
  - cargo build --target x86_64-pc-windows-gnu
  - cargo build --target x86_64-pc-windows-msvc
  - cargo build --target x86_64-unknown-linux-gnu
  - cargo test
  - cargo build --target x86_64-unknown-linux-musl

cache: cargo
