[package]
name = "threes"
version = "0.1.0"
authors = ["Chris McKee <cmckee41@qub.ac.uk>"]
build = "build.rs"

[dependencies]
rand = "*"
getopts = "*"

[dependencies.sdl2]
version = "0.30"
default-features = false
features = ["image"]