[package]
name = "threes"
version = "0.1.0"
authors = ["Chris McKee <cmckee41@qub.ac.uk>"]
build = "build.rs"

[dependencies]
rand = "0.6"
getopts = "*"

[build-dependencies]
zip = "0.4.0"

[dependencies.sdl2]
version = "0.30"
default-features = false
features = ["image"]